# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: prevac_cc_updater
  pool: 5
  host: localhost
  username: root
  password: root
  socket: /tmp/mysql.sock
